"""Add notes field to readers

Revision ID: a75d4dd8dfa8
Revises: 70fc12935315
Create Date: 2026-04-28 01:02:03.026762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75d4dd8dfa8'
down_revision: Union[str, Sequence[str], None] = '70fc12935315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readers', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readers', 'notes')
    # ### end Alembic commands ###
